from enum import Enum

class UserState(Enum):
    OFFLINE = "OFFLINE"
    WORKING = "WORKING"
    SHORT_BREAK = "ON_BREAK_SHORT"
    LUNCH_BREAK = "ON_BREAK_LUNCH"
    EXTENDED_BREAK = "ON_BREAK_EXTENDED"
    AFTER_HOURS = "AFTER_HOURS"
    ON_LEAVE = "ON_LEAVE"
    REMOTE_WORKING = "REMOTE_WORKING"
    SICK = "SICK"
    UNKNOWN = "UNKNOWN"
